apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: spring-boot
  spec:
    containers:
    - name: server
      image: sleshchenko/petclinic
      ports:
      - containerPort: 8080
        protocol: TCP
    - name: mysql
      image: centos/mysql-57-centos7
      env:
      - name: MYSQL_USER
        value: petclinic
      - name: MYSQL_ROOT_PASSWORD
        value: petclinic
      - name: MYSQL_PASSWORD
        value: petclinic
      - name: MYSQL_DATABASE
        value: petclinic
      ports:
      - containerPort: 3306
        protocol: TCP
- kind: Service
  apiVersion: v1
  metadata:
    name: petclinic
  spec:
    ports:
      - name: web
        port: 8080
        targetPort: 8080
    selector:
      name: petclinic
- kind: Service
  apiVersion: v1
  metadata:
    name: mysql
  spec:
    ports:
      - name: mysql
        port: 3306
        targetPort: 3360
    selector:
      name: petclinic
